DROP TABLE FLIGHTAVAILABILITY IF EXISTS
CREATE TABLE FLIGHTAVAILABILITY (FLIGHT_ID CHAR(6) NOT NULL, SEGMENT_NUMBER INTEGER NOT NULL, FLIGHT_DATE DATE NOT NULL, ECONOMY_SEATS_TAKEN INTEGER DEFAULT 0, BUSINESS_SEATS_TAKEN INTEGER DEFAULT 0, FIRSTCLASS_SEATS_TAKEN INTEGER DEFAULT 0 );
ALTER TABLE FLIGHTAVAILABILITY ADD CONSTRAINT FLIGHTAVAIL_PK Primary Key (FLIGHT_ID, SEGMENT_NUMBER, FLIGHT_DATE);